// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that Auditor does implement biz.Auditor.
// If this is not the case, regenerate this file with mockery.
var _ biz.Auditor = &Auditor{}

// Auditor is a mock implementation of biz.Auditor.
//
//	func TestSomethingThatUsesAuditor(t *testing.T) {
//
//		// make and configure a mocked biz.Auditor
//		mockedAuditor := &Auditor{
//			CheckFunc: func(ctx context.Context, url string) (bool, string, error) {
//				panic("mock out the Check method")
//			},
//		}
//
//		// use mockedAuditor in code that requires biz.Auditor
//		// and then make assertions.
//
//	}
type Auditor struct {
	// CheckFunc mocks the Check method.
	CheckFunc func(ctx context.Context, url string) (bool, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Check holds details about calls to the Check method.
		Check []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
		}
	}
	lockCheck sync.RWMutex
}

// Check calls CheckFunc.
func (mock *Auditor) Check(ctx context.Context, url string) (bool, string, error) {
	if mock.CheckFunc == nil {
		panic("Auditor.CheckFunc: method is nil but Auditor.Check was just called")
	}
	callInfo := struct {
		Ctx context.Context
		URL string
	}{
		Ctx: ctx,
		URL: url,
	}
	mock.lockCheck.Lock()
	mock.calls.Check = append(mock.calls.Check, callInfo)
	mock.lockCheck.Unlock()
	return mock.CheckFunc(ctx, url)
}

// CheckCalls gets all the calls that were made to Check.
// Check the length with:
//
//	len(mockedAuditor.CheckCalls())
func (mock *Auditor) CheckCalls() []struct {
	Ctx context.Context
	URL string
} {
	var calls []struct {
		Ctx context.Context
		URL string
	}
	mock.lockCheck.RLock()
	calls = mock.calls.Check
	mock.lockCheck.RUnlock()
	return calls
}
