// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that AvatarRepo does implement biz.AvatarRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.AvatarRepo = &AvatarRepo{}

// AvatarRepo is a mock implementation of biz.AvatarRepo.
//
//	func TestSomethingThatUsesAvatarRepo(t *testing.T) {
//
//		// make and configure a mocked biz.AvatarRepo
//		mockedAvatarRepo := &AvatarRepo{
//			CreateFunc: func(ctx context.Context, avatar *biz.Avatar) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, avatar *biz.Avatar) error {
//				panic("mock out the Delete method")
//			},
//			ExistsByRawFunc: func(ctx context.Context, raw string) (bool, error) {
//				panic("mock out the ExistsByRaw method")
//			},
//			FindFunc: func(ctx context.Context, userID string, hash string) (*biz.Avatar, error) {
//				panic("mock out the Find method")
//			},
//			FindForServeFunc: func(ctx context.Context, hash string, appID string) (*biz.Avatar, error) {
//				panic("mock out the FindForServe method")
//			},
//			ListFunc: func(ctx context.Context, userID string, page int, limit int) ([]*biz.Avatar, int64, error) {
//				panic("mock out the List method")
//			},
//			RandomHashesFunc: func(ctx context.Context, n int) ([]string, error) {
//				panic("mock out the RandomHashes method")
//			},
//			TouchFunc: func(ctx context.Context, avatar *biz.Avatar) error {
//				panic("mock out the Touch method")
//			},
//		}
//
//		// use mockedAvatarRepo in code that requires biz.AvatarRepo
//		// and then make assertions.
//
//	}
type AvatarRepo struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, avatar *biz.Avatar) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, avatar *biz.Avatar) error

	// ExistsByRawFunc mocks the ExistsByRaw method.
	ExistsByRawFunc func(ctx context.Context, raw string) (bool, error)

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, userID string, hash string) (*biz.Avatar, error)

	// FindForServeFunc mocks the FindForServe method.
	FindForServeFunc func(ctx context.Context, hash string, appID string) (*biz.Avatar, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, userID string, page int, limit int) ([]*biz.Avatar, int64, error)

	// RandomHashesFunc mocks the RandomHashes method.
	RandomHashesFunc func(ctx context.Context, n int) ([]string, error)

	// TouchFunc mocks the Touch method.
	TouchFunc func(ctx context.Context, avatar *biz.Avatar) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Avatar is the avatar argument value.
			Avatar *biz.Avatar
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Avatar is the avatar argument value.
			Avatar *biz.Avatar
		}
		// ExistsByRaw holds details about calls to the ExistsByRaw method.
		ExistsByRaw []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Raw is the raw argument value.
			Raw string
		}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Hash is the hash argument value.
			Hash string
		}
		// FindForServe holds details about calls to the FindForServe method.
		FindForServe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
			// AppID is the appID argument value.
			AppID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Page is the page argument value.
			Page int
			// Limit is the limit argument value.
			Limit int
		}
		// RandomHashes holds details about calls to the RandomHashes method.
		RandomHashes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// N is the n argument value.
			N int
		}
		// Touch holds details about calls to the Touch method.
		Touch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Avatar is the avatar argument value.
			Avatar *biz.Avatar
		}
	}
	lockCreate       sync.RWMutex
	lockDelete       sync.RWMutex
	lockExistsByRaw  sync.RWMutex
	lockFind         sync.RWMutex
	lockFindForServe sync.RWMutex
	lockList         sync.RWMutex
	lockRandomHashes sync.RWMutex
	lockTouch        sync.RWMutex
}

// Create calls CreateFunc.
func (mock *AvatarRepo) Create(ctx context.Context, avatar *biz.Avatar) error {
	if mock.CreateFunc == nil {
		panic("AvatarRepo.CreateFunc: method is nil but AvatarRepo.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Avatar *biz.Avatar
	}{
		Ctx:    ctx,
		Avatar: avatar,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, avatar)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAvatarRepo.CreateCalls())
func (mock *AvatarRepo) CreateCalls() []struct {
	Ctx    context.Context
	Avatar *biz.Avatar
} {
	var calls []struct {
		Ctx    context.Context
		Avatar *biz.Avatar
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *AvatarRepo) Delete(ctx context.Context, avatar *biz.Avatar) error {
	if mock.DeleteFunc == nil {
		panic("AvatarRepo.DeleteFunc: method is nil but AvatarRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Avatar *biz.Avatar
	}{
		Ctx:    ctx,
		Avatar: avatar,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, avatar)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedAvatarRepo.DeleteCalls())
func (mock *AvatarRepo) DeleteCalls() []struct {
	Ctx    context.Context
	Avatar *biz.Avatar
} {
	var calls []struct {
		Ctx    context.Context
		Avatar *biz.Avatar
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ExistsByRaw calls ExistsByRawFunc.
func (mock *AvatarRepo) ExistsByRaw(ctx context.Context, raw string) (bool, error) {
	if mock.ExistsByRawFunc == nil {
		panic("AvatarRepo.ExistsByRawFunc: method is nil but AvatarRepo.ExistsByRaw was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Raw string
	}{
		Ctx: ctx,
		Raw: raw,
	}
	mock.lockExistsByRaw.Lock()
	mock.calls.ExistsByRaw = append(mock.calls.ExistsByRaw, callInfo)
	mock.lockExistsByRaw.Unlock()
	return mock.ExistsByRawFunc(ctx, raw)
}

// ExistsByRawCalls gets all the calls that were made to ExistsByRaw.
// Check the length with:
//
//	len(mockedAvatarRepo.ExistsByRawCalls())
func (mock *AvatarRepo) ExistsByRawCalls() []struct {
	Ctx context.Context
	Raw string
} {
	var calls []struct {
		Ctx context.Context
		Raw string
	}
	mock.lockExistsByRaw.RLock()
	calls = mock.calls.ExistsByRaw
	mock.lockExistsByRaw.RUnlock()
	return calls
}

// Find calls FindFunc.
func (mock *AvatarRepo) Find(ctx context.Context, userID string, hash string) (*biz.Avatar, error) {
	if mock.FindFunc == nil {
		panic("AvatarRepo.FindFunc: method is nil but AvatarRepo.Find was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Hash   string
	}{
		Ctx:    ctx,
		UserID: userID,
		Hash:   hash,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, userID, hash)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedAvatarRepo.FindCalls())
func (mock *AvatarRepo) FindCalls() []struct {
	Ctx    context.Context
	UserID string
	Hash   string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Hash   string
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// FindForServe calls FindForServeFunc.
func (mock *AvatarRepo) FindForServe(ctx context.Context, hash string, appID string) (*biz.Avatar, error) {
	if mock.FindForServeFunc == nil {
		panic("AvatarRepo.FindForServeFunc: method is nil but AvatarRepo.FindForServe was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Hash  string
		AppID string
	}{
		Ctx:   ctx,
		Hash:  hash,
		AppID: appID,
	}
	mock.lockFindForServe.Lock()
	mock.calls.FindForServe = append(mock.calls.FindForServe, callInfo)
	mock.lockFindForServe.Unlock()
	return mock.FindForServeFunc(ctx, hash, appID)
}

// FindForServeCalls gets all the calls that were made to FindForServe.
// Check the length with:
//
//	len(mockedAvatarRepo.FindForServeCalls())
func (mock *AvatarRepo) FindForServeCalls() []struct {
	Ctx   context.Context
	Hash  string
	AppID string
} {
	var calls []struct {
		Ctx   context.Context
		Hash  string
		AppID string
	}
	mock.lockFindForServe.RLock()
	calls = mock.calls.FindForServe
	mock.lockFindForServe.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *AvatarRepo) List(ctx context.Context, userID string, page int, limit int) ([]*biz.Avatar, int64, error) {
	if mock.ListFunc == nil {
		panic("AvatarRepo.ListFunc: method is nil but AvatarRepo.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Page   int
		Limit  int
	}{
		Ctx:    ctx,
		UserID: userID,
		Page:   page,
		Limit:  limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, userID, page, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedAvatarRepo.ListCalls())
func (mock *AvatarRepo) ListCalls() []struct {
	Ctx    context.Context
	UserID string
	Page   int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Page   int
		Limit  int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// RandomHashes calls RandomHashesFunc.
func (mock *AvatarRepo) RandomHashes(ctx context.Context, n int) ([]string, error) {
	if mock.RandomHashesFunc == nil {
		panic("AvatarRepo.RandomHashesFunc: method is nil but AvatarRepo.RandomHashes was just called")
	}
	callInfo := struct {
		Ctx context.Context
		N   int
	}{
		Ctx: ctx,
		N:   n,
	}
	mock.lockRandomHashes.Lock()
	mock.calls.RandomHashes = append(mock.calls.RandomHashes, callInfo)
	mock.lockRandomHashes.Unlock()
	return mock.RandomHashesFunc(ctx, n)
}

// RandomHashesCalls gets all the calls that were made to RandomHashes.
// Check the length with:
//
//	len(mockedAvatarRepo.RandomHashesCalls())
func (mock *AvatarRepo) RandomHashesCalls() []struct {
	Ctx context.Context
	N   int
} {
	var calls []struct {
		Ctx context.Context
		N   int
	}
	mock.lockRandomHashes.RLock()
	calls = mock.calls.RandomHashes
	mock.lockRandomHashes.RUnlock()
	return calls
}

// Touch calls TouchFunc.
func (mock *AvatarRepo) Touch(ctx context.Context, avatar *biz.Avatar) error {
	if mock.TouchFunc == nil {
		panic("AvatarRepo.TouchFunc: method is nil but AvatarRepo.Touch was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Avatar *biz.Avatar
	}{
		Ctx:    ctx,
		Avatar: avatar,
	}
	mock.lockTouch.Lock()
	mock.calls.Touch = append(mock.calls.Touch, callInfo)
	mock.lockTouch.Unlock()
	return mock.TouchFunc(ctx, avatar)
}

// TouchCalls gets all the calls that were made to Touch.
// Check the length with:
//
//	len(mockedAvatarRepo.TouchCalls())
func (mock *AvatarRepo) TouchCalls() []struct {
	Ctx    context.Context
	Avatar *biz.Avatar
} {
	var calls []struct {
		Ctx    context.Context
		Avatar *biz.Avatar
	}
	mock.lockTouch.RLock()
	calls = mock.calls.Touch
	mock.lockTouch.RUnlock()
	return calls
}
