// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that Fetcher does implement biz.Fetcher.
// If this is not the case, regenerate this file with mockery.
var _ biz.Fetcher = &Fetcher{}

// Fetcher is a mock implementation of biz.Fetcher.
//
//	func TestSomethingThatUsesFetcher(t *testing.T) {
//
//		// make and configure a mocked biz.Fetcher
//		mockedFetcher := &Fetcher{
//			GravatarFunc: func(ctx context.Context, hash string) ([]byte, error) {
//				panic("mock out the Gravatar method")
//			},
//			QQFunc: func(ctx context.Context, qq string) ([]byte, error) {
//				panic("mock out the QQ method")
//			},
//		}
//
//		// use mockedFetcher in code that requires biz.Fetcher
//		// and then make assertions.
//
//	}
type Fetcher struct {
	// GravatarFunc mocks the Gravatar method.
	GravatarFunc func(ctx context.Context, hash string) ([]byte, error)

	// QQFunc mocks the QQ method.
	QQFunc func(ctx context.Context, qq string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Gravatar holds details about calls to the Gravatar method.
		Gravatar []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// QQ holds details about calls to the QQ method.
		QQ []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Qq is the qq argument value.
			Qq string
		}
	}
	lockGravatar sync.RWMutex
	lockQQ       sync.RWMutex
}

// Gravatar calls GravatarFunc.
func (mock *Fetcher) Gravatar(ctx context.Context, hash string) ([]byte, error) {
	if mock.GravatarFunc == nil {
		panic("Fetcher.GravatarFunc: method is nil but Fetcher.Gravatar was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockGravatar.Lock()
	mock.calls.Gravatar = append(mock.calls.Gravatar, callInfo)
	mock.lockGravatar.Unlock()
	return mock.GravatarFunc(ctx, hash)
}

// GravatarCalls gets all the calls that were made to Gravatar.
// Check the length with:
//
//	len(mockedFetcher.GravatarCalls())
func (mock *Fetcher) GravatarCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockGravatar.RLock()
	calls = mock.calls.Gravatar
	mock.lockGravatar.RUnlock()
	return calls
}

// QQ calls QQFunc.
func (mock *Fetcher) QQ(ctx context.Context, qq string) ([]byte, error) {
	if mock.QQFunc == nil {
		panic("Fetcher.QQFunc: method is nil but Fetcher.QQ was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Qq  string
	}{
		Ctx: ctx,
		Qq:  qq,
	}
	mock.lockQQ.Lock()
	mock.calls.QQ = append(mock.calls.QQ, callInfo)
	mock.lockQQ.Unlock()
	return mock.QQFunc(ctx, qq)
}

// QQCalls gets all the calls that were made to QQ.
// Check the length with:
//
//	len(mockedFetcher.QQCalls())
func (mock *Fetcher) QQCalls() []struct {
	Ctx context.Context
	Qq  string
} {
	var calls []struct {
		Ctx context.Context
		Qq  string
	}
	mock.lockQQ.RLock()
	calls = mock.calls.QQ
	mock.lockQQ.RUnlock()
	return calls
}
