// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that Generator does implement biz.Generator.
// If this is not the case, regenerate this file with mockery.
var _ biz.Generator = &Generator{}

// Generator is a mock implementation of biz.Generator.
//
//	func TestSomethingThatUsesGenerator(t *testing.T) {
//
//		// make and configure a mocked biz.Generator
//		mockedGenerator := &Generator{
//			GenerateFunc: func(kind string, seed string, size int, text string) ([]byte, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedGenerator in code that requires biz.Generator
//		// and then make assertions.
//
//	}
type Generator struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(kind string, seed string, size int, text string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// Kind is the kind argument value.
			Kind string
			// Seed is the seed argument value.
			Seed string
			// Size is the size argument value.
			Size int
			// Text is the text argument value.
			Text string
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *Generator) Generate(kind string, seed string, size int, text string) ([]byte, error) {
	if mock.GenerateFunc == nil {
		panic("Generator.GenerateFunc: method is nil but Generator.Generate was just called")
	}
	callInfo := struct {
		Kind string
		Seed string
		Size int
		Text string
	}{
		Kind: kind,
		Seed: seed,
		Size: size,
		Text: text,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(kind, seed, size, text)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedGenerator.GenerateCalls())
func (mock *Generator) GenerateCalls() []struct {
	Kind string
	Seed string
	Size int
	Text string
} {
	var calls []struct {
		Kind string
		Seed string
		Size int
		Text string
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}
