// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that ImageRepo does implement biz.ImageRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.ImageRepo = &ImageRepo{}

// ImageRepo is a mock implementation of biz.ImageRepo.
//
//	func TestSomethingThatUsesImageRepo(t *testing.T) {
//
//		// make and configure a mocked biz.ImageRepo
//		mockedImageRepo := &ImageRepo{
//			CreateFunc: func(ctx context.Context, image *biz.Image) error {
//				panic("mock out the Create method")
//			},
//			FindFunc: func(ctx context.Context, hash string) (*biz.Image, error) {
//				panic("mock out the Find method")
//			},
//		}
//
//		// use mockedImageRepo in code that requires biz.ImageRepo
//		// and then make assertions.
//
//	}
type ImageRepo struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, image *biz.Image) error

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, hash string) (*biz.Image, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Image is the image argument value.
			Image *biz.Image
		}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
	}
	lockCreate sync.RWMutex
	lockFind   sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ImageRepo) Create(ctx context.Context, image *biz.Image) error {
	if mock.CreateFunc == nil {
		panic("ImageRepo.CreateFunc: method is nil but ImageRepo.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Image *biz.Image
	}{
		Ctx:   ctx,
		Image: image,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, image)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedImageRepo.CreateCalls())
func (mock *ImageRepo) CreateCalls() []struct {
	Ctx   context.Context
	Image *biz.Image
} {
	var calls []struct {
		Ctx   context.Context
		Image *biz.Image
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Find calls FindFunc.
func (mock *ImageRepo) Find(ctx context.Context, hash string) (*biz.Image, error) {
	if mock.FindFunc == nil {
		panic("ImageRepo.FindFunc: method is nil but ImageRepo.Find was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, hash)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedImageRepo.FindCalls())
func (mock *ImageRepo) FindCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}
