// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that Purger does implement biz.Purger.
// If this is not the case, regenerate this file with mockery.
var _ biz.Purger = &Purger{}

// Purger is a mock implementation of biz.Purger.
//
//	func TestSomethingThatUsesPurger(t *testing.T) {
//
//		// make and configure a mocked biz.Purger
//		mockedPurger := &Purger{
//			RefreshFunc: func(ctx context.Context, urls []string) error {
//				panic("mock out the Refresh method")
//			},
//		}
//
//		// use mockedPurger in code that requires biz.Purger
//		// and then make assertions.
//
//	}
type Purger struct {
	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(ctx context.Context, urls []string) error

	// calls tracks calls to the methods.
	calls struct {
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Urls is the urls argument value.
			Urls []string
		}
	}
	lockRefresh sync.RWMutex
}

// Refresh calls RefreshFunc.
func (mock *Purger) Refresh(ctx context.Context, urls []string) error {
	if mock.RefreshFunc == nil {
		panic("Purger.RefreshFunc: method is nil but Purger.Refresh was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Urls []string
	}{
		Ctx:  ctx,
		Urls: urls,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(ctx, urls)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedPurger.RefreshCalls())
func (mock *Purger) RefreshCalls() []struct {
	Ctx  context.Context
	Urls []string
} {
	var calls []struct {
		Ctx  context.Context
		Urls []string
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}
