// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that QQHashes does implement biz.QQHashes.
// If this is not the case, regenerate this file with mockery.
var _ biz.QQHashes = &QQHashes{}

// QQHashes is a mock implementation of biz.QQHashes.
//
//	func TestSomethingThatUsesQQHashes(t *testing.T) {
//
//		// make and configure a mocked biz.QQHashes
//		mockedQQHashes := &QQHashes{
//			LookupFunc: func(hash string) (uint32, bool) {
//				panic("mock out the Lookup method")
//			},
//		}
//
//		// use mockedQQHashes in code that requires biz.QQHashes
//		// and then make assertions.
//
//	}
type QQHashes struct {
	// LookupFunc mocks the Lookup method.
	LookupFunc func(hash string) (uint32, bool)

	// calls tracks calls to the methods.
	calls struct {
		// Lookup holds details about calls to the Lookup method.
		Lookup []struct {
			// Hash is the hash argument value.
			Hash string
		}
	}
	lockLookup sync.RWMutex
}

// Lookup calls LookupFunc.
func (mock *QQHashes) Lookup(hash string) (uint32, bool) {
	if mock.LookupFunc == nil {
		panic("QQHashes.LookupFunc: method is nil but QQHashes.Lookup was just called")
	}
	callInfo := struct {
		Hash string
	}{
		Hash: hash,
	}
	mock.lockLookup.Lock()
	mock.calls.Lookup = append(mock.calls.Lookup, callInfo)
	mock.lockLookup.Unlock()
	return mock.LookupFunc(hash)
}

// LookupCalls gets all the calls that were made to Lookup.
// Check the length with:
//
//	len(mockedQQHashes.LookupCalls())
func (mock *QQHashes) LookupCalls() []struct {
	Hash string
} {
	var calls []struct {
		Hash string
	}
	mock.lockLookup.RLock()
	calls = mock.calls.Lookup
	mock.lockLookup.RUnlock()
	return calls
}
