// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"
	"time"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that Store does implement biz.Store.
// If this is not the case, regenerate this file with mockery.
var _ biz.Store = &Store{}

// Store is a mock implementation of biz.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked biz.Store
//		mockedStore := &Store{
//			PurgeCacheFunc: func(ctx context.Context, olderThan time.Duration) error {
//				panic("mock out the PurgeCache method")
//			},
//			ReadAppAvatarFunc: func(appID string, sha256 string) ([]byte, error) {
//				panic("mock out the ReadAppAvatar method")
//			},
//			ReadAvatarFunc: func(sha256 string) ([]byte, error) {
//				panic("mock out the ReadAvatar method")
//			},
//			ReadCacheFunc: func(kind string, key string) ([]byte, time.Time, bool) {
//				panic("mock out the ReadCache method")
//			},
//			RemoveAvatarFunc: func(sha256 string) error {
//				panic("mock out the RemoveAvatar method")
//			},
//			WriteAvatarFunc: func(sha256 string, img []byte) error {
//				panic("mock out the WriteAvatar method")
//			},
//			WriteCacheFunc: func(kind string, key string, img []byte) error {
//				panic("mock out the WriteCache method")
//			},
//			WriteCheckerFunc: func(imgHash string, img []byte) error {
//				panic("mock out the WriteChecker method")
//			},
//		}
//
//		// use mockedStore in code that requires biz.Store
//		// and then make assertions.
//
//	}
type Store struct {
	// PurgeCacheFunc mocks the PurgeCache method.
	PurgeCacheFunc func(ctx context.Context, olderThan time.Duration) error

	// ReadAppAvatarFunc mocks the ReadAppAvatar method.
	ReadAppAvatarFunc func(appID string, sha256 string) ([]byte, error)

	// ReadAvatarFunc mocks the ReadAvatar method.
	ReadAvatarFunc func(sha256 string) ([]byte, error)

	// ReadCacheFunc mocks the ReadCache method.
	ReadCacheFunc func(kind string, key string) ([]byte, time.Time, bool)

	// RemoveAvatarFunc mocks the RemoveAvatar method.
	RemoveAvatarFunc func(sha256 string) error

	// WriteAvatarFunc mocks the WriteAvatar method.
	WriteAvatarFunc func(sha256 string, img []byte) error

	// WriteCacheFunc mocks the WriteCache method.
	WriteCacheFunc func(kind string, key string, img []byte) error

	// WriteCheckerFunc mocks the WriteChecker method.
	WriteCheckerFunc func(imgHash string, img []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// PurgeCache holds details about calls to the PurgeCache method.
		PurgeCache []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OlderThan is the olderThan argument value.
			OlderThan time.Duration
		}
		// ReadAppAvatar holds details about calls to the ReadAppAvatar method.
		ReadAppAvatar []struct {
			// AppID is the appID argument value.
			AppID string
			// Sha256 is the sha256 argument value.
			Sha256 string
		}
		// ReadAvatar holds details about calls to the ReadAvatar method.
		ReadAvatar []struct {
			// Sha256 is the sha256 argument value.
			Sha256 string
		}
		// ReadCache holds details about calls to the ReadCache method.
		ReadCache []struct {
			// Kind is the kind argument value.
			Kind string
			// Key is the key argument value.
			Key string
		}
		// RemoveAvatar holds details about calls to the RemoveAvatar method.
		RemoveAvatar []struct {
			// Sha256 is the sha256 argument value.
			Sha256 string
		}
		// WriteAvatar holds details about calls to the WriteAvatar method.
		WriteAvatar []struct {
			// Sha256 is the sha256 argument value.
			Sha256 string
			// Img is the img argument value.
			Img []byte
		}
		// WriteCache holds details about calls to the WriteCache method.
		WriteCache []struct {
			// Kind is the kind argument value.
			Kind string
			// Key is the key argument value.
			Key string
			// Img is the img argument value.
			Img []byte
		}
		// WriteChecker holds details about calls to the WriteChecker method.
		WriteChecker []struct {
			// ImgHash is the imgHash argument value.
			ImgHash string
			// Img is the img argument value.
			Img []byte
		}
	}
	lockPurgeCache    sync.RWMutex
	lockReadAppAvatar sync.RWMutex
	lockReadAvatar    sync.RWMutex
	lockReadCache     sync.RWMutex
	lockRemoveAvatar  sync.RWMutex
	lockWriteAvatar   sync.RWMutex
	lockWriteCache    sync.RWMutex
	lockWriteChecker  sync.RWMutex
}

// PurgeCache calls PurgeCacheFunc.
func (mock *Store) PurgeCache(ctx context.Context, olderThan time.Duration) error {
	if mock.PurgeCacheFunc == nil {
		panic("Store.PurgeCacheFunc: method is nil but Store.PurgeCache was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OlderThan time.Duration
	}{
		Ctx:       ctx,
		OlderThan: olderThan,
	}
	mock.lockPurgeCache.Lock()
	mock.calls.PurgeCache = append(mock.calls.PurgeCache, callInfo)
	mock.lockPurgeCache.Unlock()
	return mock.PurgeCacheFunc(ctx, olderThan)
}

// PurgeCacheCalls gets all the calls that were made to PurgeCache.
// Check the length with:
//
//	len(mockedStore.PurgeCacheCalls())
func (mock *Store) PurgeCacheCalls() []struct {
	Ctx       context.Context
	OlderThan time.Duration
} {
	var calls []struct {
		Ctx       context.Context
		OlderThan time.Duration
	}
	mock.lockPurgeCache.RLock()
	calls = mock.calls.PurgeCache
	mock.lockPurgeCache.RUnlock()
	return calls
}

// ReadAppAvatar calls ReadAppAvatarFunc.
func (mock *Store) ReadAppAvatar(appID string, sha256 string) ([]byte, error) {
	if mock.ReadAppAvatarFunc == nil {
		panic("Store.ReadAppAvatarFunc: method is nil but Store.ReadAppAvatar was just called")
	}
	callInfo := struct {
		AppID  string
		Sha256 string
	}{
		AppID:  appID,
		Sha256: sha256,
	}
	mock.lockReadAppAvatar.Lock()
	mock.calls.ReadAppAvatar = append(mock.calls.ReadAppAvatar, callInfo)
	mock.lockReadAppAvatar.Unlock()
	return mock.ReadAppAvatarFunc(appID, sha256)
}

// ReadAppAvatarCalls gets all the calls that were made to ReadAppAvatar.
// Check the length with:
//
//	len(mockedStore.ReadAppAvatarCalls())
func (mock *Store) ReadAppAvatarCalls() []struct {
	AppID  string
	Sha256 string
} {
	var calls []struct {
		AppID  string
		Sha256 string
	}
	mock.lockReadAppAvatar.RLock()
	calls = mock.calls.ReadAppAvatar
	mock.lockReadAppAvatar.RUnlock()
	return calls
}

// ReadAvatar calls ReadAvatarFunc.
func (mock *Store) ReadAvatar(sha256 string) ([]byte, error) {
	if mock.ReadAvatarFunc == nil {
		panic("Store.ReadAvatarFunc: method is nil but Store.ReadAvatar was just called")
	}
	callInfo := struct {
		Sha256 string
	}{
		Sha256: sha256,
	}
	mock.lockReadAvatar.Lock()
	mock.calls.ReadAvatar = append(mock.calls.ReadAvatar, callInfo)
	mock.lockReadAvatar.Unlock()
	return mock.ReadAvatarFunc(sha256)
}

// ReadAvatarCalls gets all the calls that were made to ReadAvatar.
// Check the length with:
//
//	len(mockedStore.ReadAvatarCalls())
func (mock *Store) ReadAvatarCalls() []struct {
	Sha256 string
} {
	var calls []struct {
		Sha256 string
	}
	mock.lockReadAvatar.RLock()
	calls = mock.calls.ReadAvatar
	mock.lockReadAvatar.RUnlock()
	return calls
}

// ReadCache calls ReadCacheFunc.
func (mock *Store) ReadCache(kind string, key string) ([]byte, time.Time, bool) {
	if mock.ReadCacheFunc == nil {
		panic("Store.ReadCacheFunc: method is nil but Store.ReadCache was just called")
	}
	callInfo := struct {
		Kind string
		Key  string
	}{
		Kind: kind,
		Key:  key,
	}
	mock.lockReadCache.Lock()
	mock.calls.ReadCache = append(mock.calls.ReadCache, callInfo)
	mock.lockReadCache.Unlock()
	return mock.ReadCacheFunc(kind, key)
}

// ReadCacheCalls gets all the calls that were made to ReadCache.
// Check the length with:
//
//	len(mockedStore.ReadCacheCalls())
func (mock *Store) ReadCacheCalls() []struct {
	Kind string
	Key  string
} {
	var calls []struct {
		Kind string
		Key  string
	}
	mock.lockReadCache.RLock()
	calls = mock.calls.ReadCache
	mock.lockReadCache.RUnlock()
	return calls
}

// RemoveAvatar calls RemoveAvatarFunc.
func (mock *Store) RemoveAvatar(sha256 string) error {
	if mock.RemoveAvatarFunc == nil {
		panic("Store.RemoveAvatarFunc: method is nil but Store.RemoveAvatar was just called")
	}
	callInfo := struct {
		Sha256 string
	}{
		Sha256: sha256,
	}
	mock.lockRemoveAvatar.Lock()
	mock.calls.RemoveAvatar = append(mock.calls.RemoveAvatar, callInfo)
	mock.lockRemoveAvatar.Unlock()
	return mock.RemoveAvatarFunc(sha256)
}

// RemoveAvatarCalls gets all the calls that were made to RemoveAvatar.
// Check the length with:
//
//	len(mockedStore.RemoveAvatarCalls())
func (mock *Store) RemoveAvatarCalls() []struct {
	Sha256 string
} {
	var calls []struct {
		Sha256 string
	}
	mock.lockRemoveAvatar.RLock()
	calls = mock.calls.RemoveAvatar
	mock.lockRemoveAvatar.RUnlock()
	return calls
}

// WriteAvatar calls WriteAvatarFunc.
func (mock *Store) WriteAvatar(sha256 string, img []byte) error {
	if mock.WriteAvatarFunc == nil {
		panic("Store.WriteAvatarFunc: method is nil but Store.WriteAvatar was just called")
	}
	callInfo := struct {
		Sha256 string
		Img    []byte
	}{
		Sha256: sha256,
		Img:    img,
	}
	mock.lockWriteAvatar.Lock()
	mock.calls.WriteAvatar = append(mock.calls.WriteAvatar, callInfo)
	mock.lockWriteAvatar.Unlock()
	return mock.WriteAvatarFunc(sha256, img)
}

// WriteAvatarCalls gets all the calls that were made to WriteAvatar.
// Check the length with:
//
//	len(mockedStore.WriteAvatarCalls())
func (mock *Store) WriteAvatarCalls() []struct {
	Sha256 string
	Img    []byte
} {
	var calls []struct {
		Sha256 string
		Img    []byte
	}
	mock.lockWriteAvatar.RLock()
	calls = mock.calls.WriteAvatar
	mock.lockWriteAvatar.RUnlock()
	return calls
}

// WriteCache calls WriteCacheFunc.
func (mock *Store) WriteCache(kind string, key string, img []byte) error {
	if mock.WriteCacheFunc == nil {
		panic("Store.WriteCacheFunc: method is nil but Store.WriteCache was just called")
	}
	callInfo := struct {
		Kind string
		Key  string
		Img  []byte
	}{
		Kind: kind,
		Key:  key,
		Img:  img,
	}
	mock.lockWriteCache.Lock()
	mock.calls.WriteCache = append(mock.calls.WriteCache, callInfo)
	mock.lockWriteCache.Unlock()
	return mock.WriteCacheFunc(kind, key, img)
}

// WriteCacheCalls gets all the calls that were made to WriteCache.
// Check the length with:
//
//	len(mockedStore.WriteCacheCalls())
func (mock *Store) WriteCacheCalls() []struct {
	Kind string
	Key  string
	Img  []byte
} {
	var calls []struct {
		Kind string
		Key  string
		Img  []byte
	}
	mock.lockWriteCache.RLock()
	calls = mock.calls.WriteCache
	mock.lockWriteCache.RUnlock()
	return calls
}

// WriteChecker calls WriteCheckerFunc.
func (mock *Store) WriteChecker(imgHash string, img []byte) error {
	if mock.WriteCheckerFunc == nil {
		panic("Store.WriteCheckerFunc: method is nil but Store.WriteChecker was just called")
	}
	callInfo := struct {
		ImgHash string
		Img     []byte
	}{
		ImgHash: imgHash,
		Img:     img,
	}
	mock.lockWriteChecker.Lock()
	mock.calls.WriteChecker = append(mock.calls.WriteChecker, callInfo)
	mock.lockWriteChecker.Unlock()
	return mock.WriteCheckerFunc(imgHash, img)
}

// WriteCheckerCalls gets all the calls that were made to WriteChecker.
// Check the length with:
//
//	len(mockedStore.WriteCheckerCalls())
func (mock *Store) WriteCheckerCalls() []struct {
	ImgHash string
	Img     []byte
} {
	var calls []struct {
		ImgHash string
		Img     []byte
	}
	mock.lockWriteChecker.RLock()
	calls = mock.calls.WriteChecker
	mock.lockWriteChecker.RUnlock()
	return calls
}
