// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that TxRunner does implement biz.TxRunner.
// If this is not the case, regenerate this file with mockery.
var _ biz.TxRunner = &TxRunner{}

// TxRunner is a mock implementation of biz.TxRunner.
//
//	func TestSomethingThatUsesTxRunner(t *testing.T) {
//
//		// make and configure a mocked biz.TxRunner
//		mockedTxRunner := &TxRunner{
//			RunFunc: func(ctx context.Context, fn func(ctx context.Context) error) error {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedTxRunner in code that requires biz.TxRunner
//		// and then make assertions.
//
//	}
type TxRunner struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, fn func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *TxRunner) Run(ctx context.Context, fn func(ctx context.Context) error) error {
	if mock.RunFunc == nil {
		panic("TxRunner.RunFunc: method is nil but TxRunner.Run was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, fn)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedTxRunner.RunCalls())
func (mock *TxRunner) RunCalls() []struct {
	Ctx context.Context
	Fn  func(ctx context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
