// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/avatar/biz"
)

// Ensure that Users does implement biz.Users.
// If this is not the case, regenerate this file with mockery.
var _ biz.Users = &Users{}

// Users is a mock implementation of biz.Users.
//
//	func TestSomethingThatUsesUsers(t *testing.T) {
//
//		// make and configure a mocked biz.Users
//		mockedUsers := &Users{
//			NicknameFunc: func(ctx context.Context, userID string) (string, error) {
//				panic("mock out the Nickname method")
//			},
//		}
//
//		// use mockedUsers in code that requires biz.Users
//		// and then make assertions.
//
//	}
type Users struct {
	// NicknameFunc mocks the Nickname method.
	NicknameFunc func(ctx context.Context, userID string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Nickname holds details about calls to the Nickname method.
		Nickname []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockNickname sync.RWMutex
}

// Nickname calls NicknameFunc.
func (mock *Users) Nickname(ctx context.Context, userID string) (string, error) {
	if mock.NicknameFunc == nil {
		panic("Users.NicknameFunc: method is nil but Users.Nickname was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockNickname.Lock()
	mock.calls.Nickname = append(mock.calls.Nickname, callInfo)
	mock.lockNickname.Unlock()
	return mock.NicknameFunc(ctx, userID)
}

// NicknameCalls gets all the calls that were made to Nickname.
// Check the length with:
//
//	len(mockedUsers.NicknameCalls())
func (mock *Users) NicknameCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockNickname.RLock()
	calls = mock.calls.Nickname
	mock.lockNickname.RUnlock()
	return calls
}
