// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/system/biz"
)

// Ensure that Avatars does implement biz.Avatars.
// If this is not the case, regenerate this file with mockery.
var _ biz.Avatars = &Avatars{}

// Avatars is a mock implementation of biz.Avatars.
//
//	func TestSomethingThatUsesAvatars(t *testing.T) {
//
//		// make and configure a mocked biz.Avatars
//		mockedAvatars := &Avatars{
//			RandomHashesFunc: func(ctx context.Context, n int) ([]string, error) {
//				panic("mock out the RandomHashes method")
//			},
//		}
//
//		// use mockedAvatars in code that requires biz.Avatars
//		// and then make assertions.
//
//	}
type Avatars struct {
	// RandomHashesFunc mocks the RandomHashes method.
	RandomHashesFunc func(ctx context.Context, n int) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// RandomHashes holds details about calls to the RandomHashes method.
		RandomHashes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// N is the n argument value.
			N int
		}
	}
	lockRandomHashes sync.RWMutex
}

// RandomHashes calls RandomHashesFunc.
func (mock *Avatars) RandomHashes(ctx context.Context, n int) ([]string, error) {
	if mock.RandomHashesFunc == nil {
		panic("Avatars.RandomHashesFunc: method is nil but Avatars.RandomHashes was just called")
	}
	callInfo := struct {
		Ctx context.Context
		N   int
	}{
		Ctx: ctx,
		N:   n,
	}
	mock.lockRandomHashes.Lock()
	mock.calls.RandomHashes = append(mock.calls.RandomHashes, callInfo)
	mock.lockRandomHashes.Unlock()
	return mock.RandomHashesFunc(ctx, n)
}

// RandomHashesCalls gets all the calls that were made to RandomHashes.
// Check the length with:
//
//	len(mockedAvatars.RandomHashesCalls())
func (mock *Avatars) RandomHashesCalls() []struct {
	Ctx context.Context
	N   int
} {
	var calls []struct {
		Ctx context.Context
		N   int
	}
	mock.lockRandomHashes.RLock()
	calls = mock.calls.RandomHashes
	mock.lockRandomHashes.RUnlock()
	return calls
}
