// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"
	"time"

	"github.com/weavatar/weavatar/internal/system/biz"
)

// Ensure that Usage does implement biz.Usage.
// If this is not the case, regenerate this file with mockery.
var _ biz.Usage = &Usage{}

// Usage is a mock implementation of biz.Usage.
//
//	func TestSomethingThatUsesUsage(t *testing.T) {
//
//		// make and configure a mocked biz.Usage
//		mockedUsage := &Usage{
//			FetchFunc: func(ctx context.Context, domain string, start time.Time, end time.Time) (uint, error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedUsage in code that requires biz.Usage
//		// and then make assertions.
//
//	}
type Usage struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, domain string, start time.Time, end time.Time) (uint, error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Domain is the domain argument value.
			Domain string
			// Start is the start argument value.
			Start time.Time
			// End is the end argument value.
			End time.Time
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *Usage) Fetch(ctx context.Context, domain string, start time.Time, end time.Time) (uint, error) {
	if mock.FetchFunc == nil {
		panic("Usage.FetchFunc: method is nil but Usage.Fetch was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Domain string
		Start  time.Time
		End    time.Time
	}{
		Ctx:    ctx,
		Domain: domain,
		Start:  start,
		End:    end,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, domain, start, end)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedUsage.FetchCalls())
func (mock *Usage) FetchCalls() []struct {
	Ctx    context.Context
	Domain string
	Start  time.Time
	End    time.Time
} {
	var calls []struct {
		Ctx    context.Context
		Domain string
		Start  time.Time
		End    time.Time
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}
