// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/user/biz"
)

// Ensure that OAuthProvider does implement biz.OAuthProvider.
// If this is not the case, regenerate this file with mockery.
var _ biz.OAuthProvider = &OAuthProvider{}

// OAuthProvider is a mock implementation of biz.OAuthProvider.
//
//	func TestSomethingThatUsesOAuthProvider(t *testing.T) {
//
//		// make and configure a mocked biz.OAuthProvider
//		mockedOAuthProvider := &OAuthProvider{
//			ExchangeFunc: func(ctx context.Context, code string, redirectURI string) (biz.Identity, error) {
//				panic("mock out the Exchange method")
//			},
//		}
//
//		// use mockedOAuthProvider in code that requires biz.OAuthProvider
//		// and then make assertions.
//
//	}
type OAuthProvider struct {
	// ExchangeFunc mocks the Exchange method.
	ExchangeFunc func(ctx context.Context, code string, redirectURI string) (biz.Identity, error)

	// calls tracks calls to the methods.
	calls struct {
		// Exchange holds details about calls to the Exchange method.
		Exchange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
			// RedirectURI is the redirectURI argument value.
			RedirectURI string
		}
	}
	lockExchange sync.RWMutex
}

// Exchange calls ExchangeFunc.
func (mock *OAuthProvider) Exchange(ctx context.Context, code string, redirectURI string) (biz.Identity, error) {
	if mock.ExchangeFunc == nil {
		panic("OAuthProvider.ExchangeFunc: method is nil but OAuthProvider.Exchange was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Code        string
		RedirectURI string
	}{
		Ctx:         ctx,
		Code:        code,
		RedirectURI: redirectURI,
	}
	mock.lockExchange.Lock()
	mock.calls.Exchange = append(mock.calls.Exchange, callInfo)
	mock.lockExchange.Unlock()
	return mock.ExchangeFunc(ctx, code, redirectURI)
}

// ExchangeCalls gets all the calls that were made to Exchange.
// Check the length with:
//
//	len(mockedOAuthProvider.ExchangeCalls())
func (mock *OAuthProvider) ExchangeCalls() []struct {
	Ctx         context.Context
	Code        string
	RedirectURI string
} {
	var calls []struct {
		Ctx         context.Context
		Code        string
		RedirectURI string
	}
	mock.lockExchange.RLock()
	calls = mock.calls.Exchange
	mock.lockExchange.RUnlock()
	return calls
}
