// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"

	"github.com/weavatar/weavatar/internal/user/biz"
)

// Ensure that Tokens does implement biz.Tokens.
// If this is not the case, regenerate this file with mockery.
var _ biz.Tokens = &Tokens{}

// Tokens is a mock implementation of biz.Tokens.
//
//	func TestSomethingThatUsesTokens(t *testing.T) {
//
//		// make and configure a mocked biz.Tokens
//		mockedTokens := &Tokens{
//			IssueFunc: func(userID string) (string, error) {
//				panic("mock out the Issue method")
//			},
//		}
//
//		// use mockedTokens in code that requires biz.Tokens
//		// and then make assertions.
//
//	}
type Tokens struct {
	// IssueFunc mocks the Issue method.
	IssueFunc func(userID string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Issue holds details about calls to the Issue method.
		Issue []struct {
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockIssue sync.RWMutex
}

// Issue calls IssueFunc.
func (mock *Tokens) Issue(userID string) (string, error) {
	if mock.IssueFunc == nil {
		panic("Tokens.IssueFunc: method is nil but Tokens.Issue was just called")
	}
	callInfo := struct {
		UserID string
	}{
		UserID: userID,
	}
	mock.lockIssue.Lock()
	mock.calls.Issue = append(mock.calls.Issue, callInfo)
	mock.lockIssue.Unlock()
	return mock.IssueFunc(userID)
}

// IssueCalls gets all the calls that were made to Issue.
// Check the length with:
//
//	len(mockedTokens.IssueCalls())
func (mock *Tokens) IssueCalls() []struct {
	UserID string
} {
	var calls []struct {
		UserID string
	}
	mock.lockIssue.RLock()
	calls = mock.calls.Issue
	mock.lockIssue.RUnlock()
	return calls
}
