// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/user/biz"
)

// Ensure that UserRepo does implement biz.UserRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.UserRepo = &UserRepo{}

// UserRepo is a mock implementation of biz.UserRepo.
//
//	func TestSomethingThatUsesUserRepo(t *testing.T) {
//
//		// make and configure a mocked biz.UserRepo
//		mockedUserRepo := &UserRepo{
//			CreateFunc: func(ctx context.Context, user *biz.User) error {
//				panic("mock out the Create method")
//			},
//			FindFunc: func(ctx context.Context, id string) (*biz.User, error) {
//				panic("mock out the Find method")
//			},
//			FindByUnionIDFunc: func(ctx context.Context, unionID string) (*biz.User, error) {
//				panic("mock out the FindByUnionID method")
//			},
//			UpdateFunc: func(ctx context.Context, user *biz.User) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepo in code that requires biz.UserRepo
//		// and then make assertions.
//
//	}
type UserRepo struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *biz.User) error

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, id string) (*biz.User, error)

	// FindByUnionIDFunc mocks the FindByUnionID method.
	FindByUnionIDFunc func(ctx context.Context, unionID string) (*biz.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, user *biz.User) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *biz.User
		}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// FindByUnionID holds details about calls to the FindByUnionID method.
		FindByUnionID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UnionID is the unionID argument value.
			UnionID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *biz.User
		}
	}
	lockCreate        sync.RWMutex
	lockFind          sync.RWMutex
	lockFindByUnionID sync.RWMutex
	lockUpdate        sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepo) Create(ctx context.Context, user *biz.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepo.CreateFunc: method is nil but UserRepo.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *biz.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepo.CreateCalls())
func (mock *UserRepo) CreateCalls() []struct {
	Ctx  context.Context
	User *biz.User
} {
	var calls []struct {
		Ctx  context.Context
		User *biz.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Find calls FindFunc.
func (mock *UserRepo) Find(ctx context.Context, id string) (*biz.User, error) {
	if mock.FindFunc == nil {
		panic("UserRepo.FindFunc: method is nil but UserRepo.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, id)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedUserRepo.FindCalls())
func (mock *UserRepo) FindCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// FindByUnionID calls FindByUnionIDFunc.
func (mock *UserRepo) FindByUnionID(ctx context.Context, unionID string) (*biz.User, error) {
	if mock.FindByUnionIDFunc == nil {
		panic("UserRepo.FindByUnionIDFunc: method is nil but UserRepo.FindByUnionID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		UnionID string
	}{
		Ctx:     ctx,
		UnionID: unionID,
	}
	mock.lockFindByUnionID.Lock()
	mock.calls.FindByUnionID = append(mock.calls.FindByUnionID, callInfo)
	mock.lockFindByUnionID.Unlock()
	return mock.FindByUnionIDFunc(ctx, unionID)
}

// FindByUnionIDCalls gets all the calls that were made to FindByUnionID.
// Check the length with:
//
//	len(mockedUserRepo.FindByUnionIDCalls())
func (mock *UserRepo) FindByUnionIDCalls() []struct {
	Ctx     context.Context
	UnionID string
} {
	var calls []struct {
		Ctx     context.Context
		UnionID string
	}
	mock.lockFindByUnionID.RLock()
	calls = mock.calls.FindByUnionID
	mock.lockFindByUnionID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepo) Update(ctx context.Context, user *biz.User) error {
	if mock.UpdateFunc == nil {
		panic("UserRepo.UpdateFunc: method is nil but UserRepo.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *biz.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepo.UpdateCalls())
func (mock *UserRepo) UpdateCalls() []struct {
	Ctx  context.Context
	User *biz.User
} {
	var calls []struct {
		Ctx  context.Context
		User *biz.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
