// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-rat/fiber-skeleton/internal/app"
	"github.com/go-rat/fiber-skeleton/internal/bootstrap"
	"github.com/go-rat/fiber-skeleton/internal/data"
	"github.com/go-rat/fiber-skeleton/internal/http/middleware"
	"github.com/go-rat/fiber-skeleton/internal/route"
	"github.com/go-rat/fiber-skeleton/internal/service"
)

import (
	_ "time/tzdata"
)

// Injectors from wire.go:

// initApp init application.
func initApp() (*app.App, error) {
	koanf, err := bootstrap.NewConf()
	if err != nil {
		return nil, err
	}
	middlewares := middleware.NewMiddlewares(koanf)
	logger := bootstrap.NewLog(koanf)
	db, err := bootstrap.NewDB(koanf, logger)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(db)
	userService := service.NewUserService(userRepo)
	http := route.NewHttp(userService)
	ws := route.NewWs()
	fiberApp := bootstrap.NewRouter(koanf, middlewares, http, ws)
	gormigrate := bootstrap.NewMigrate(db)
	cron := bootstrap.NewCron(koanf, logger)
	validation := bootstrap.NewValidator(db)
	appApp := app.NewApp(koanf, fiberApp, gormigrate, cron, validation)
	return appApp, nil
}
