// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/verifycode/biz"
)

// Ensure that MailSender does implement biz.MailSender.
// If this is not the case, regenerate this file with mockery.
var _ biz.MailSender = &MailSender{}

// MailSender is a mock implementation of biz.MailSender.
//
//	func TestSomethingThatUsesMailSender(t *testing.T) {
//
//		// make and configure a mocked biz.MailSender
//		mockedMailSender := &MailSender{
//			SendFunc: func(ctx context.Context, to string, code string) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedMailSender in code that requires biz.MailSender
//		// and then make assertions.
//
//	}
type MailSender struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, to string, code string) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// To is the to argument value.
			To string
			// Code is the code argument value.
			Code string
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *MailSender) Send(ctx context.Context, to string, code string) error {
	if mock.SendFunc == nil {
		panic("MailSender.SendFunc: method is nil but MailSender.Send was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		To   string
		Code string
	}{
		Ctx:  ctx,
		To:   to,
		Code: code,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, to, code)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedMailSender.SendCalls())
func (mock *MailSender) SendCalls() []struct {
	Ctx  context.Context
	To   string
	Code string
} {
	var calls []struct {
		Ctx  context.Context
		To   string
		Code string
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
