// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/weavatar/weavatar/internal/verifycode/biz"
)

// Ensure that SMSSender does implement biz.SMSSender.
// If this is not the case, regenerate this file with mockery.
var _ biz.SMSSender = &SMSSender{}

// SMSSender is a mock implementation of biz.SMSSender.
//
//	func TestSomethingThatUsesSMSSender(t *testing.T) {
//
//		// make and configure a mocked biz.SMSSender
//		mockedSMSSender := &SMSSender{
//			SendFunc: func(ctx context.Context, phone string, code string) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedSMSSender in code that requires biz.SMSSender
//		// and then make assertions.
//
//	}
type SMSSender struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, phone string, code string) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Phone is the phone argument value.
			Phone string
			// Code is the code argument value.
			Code string
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *SMSSender) Send(ctx context.Context, phone string, code string) error {
	if mock.SendFunc == nil {
		panic("SMSSender.SendFunc: method is nil but SMSSender.Send was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Phone string
		Code  string
	}{
		Ctx:   ctx,
		Phone: phone,
		Code:  code,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, phone, code)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedSMSSender.SendCalls())
func (mock *SMSSender) SendCalls() []struct {
	Ctx   context.Context
	Phone string
	Code  string
} {
	var calls []struct {
		Ctx   context.Context
		Phone string
		Code  string
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
