app:
  name: "weavatar"
  key: "a-long-string-with-32-characters"
  debug: true
http:
  debug: true
  prefork: false
  address: ":3000"
  domain: "weavatar.com"
  bodyLimit: 4096
  headerLimit: 4096
  reduceMemoryUsage: false
database:
  debug: true
  import: true
  socket: "/tmp/mysql.sock"
  user: "root"
  password: ""
  name: "weavatar"
mail:
  host: "smtp.example.com"
  port: 587
  user: "noreply@example.com"
  password: ""
geetest:
  id: "your-geetest-id"
  key: "your-geetest-key"
code:
  expireTime: 5
sms:
  driver: "aliyun"
  aliyun:
    accessKeyId: "your-access-key-id"
    accessKeySecret: "your-access-key-secret"
    signName: ""
    templateCode: 123456
  tencent:
    secretId: "your-secret-id"
    secretKey: "your-secret-key"
    signName: ""
    templateId: 123456
    sdkAppId: 123456
oauth:
  baseUrl: "https://account.haozi.net"
  clientID: "1234567890"
  clientSecret: "abcdef1234567890abcdef1234567890"
audit:
  driver: "aliyun"
  aliyun:
    accessKeyId: "your-access-key-id"
    accessKeySecret: "your-access-key-secret"
  cos:
    secretId: "your-secret-id"
    secretKey: "your-secret-key"
    bucket: "your-bucket.cos.ap-xx.myqcloud.com"
cdn:
  driver:
    - "baishan"
  baishan:
    token: "your-token"
  cloudflare:
    apiKey: "your-api-key"
    apiEmail: "your-email"
    zoneID: "your-zone-id"
  ctyun:
    appID: "your-app-id"
    appSecret: "your-app-secret"
  huawei:
    accessKey: "your-access-key"
    secretKey: "your-secret-key"
  starshield:
    accessKey: "your-access-key"
    secretKey: "your-secret-key"
    instanceID: "your-instance-id"
    zoneID: "your-zone-id"
  upyun:
    token: "your-token"
  wafpro:
    apiKey: "your-api-key"
    apiSecret: "your-api-secret"
  wjdun:
    apiKey: "your-api-key"
    apiSecret: "your-api-secret"
  yundun:
    username: "your-username"
    password: "your-password"
