// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-rat/fiber-skeleton/internal/app"
	"github.com/go-rat/fiber-skeleton/internal/bootstrap"
	"github.com/go-rat/fiber-skeleton/internal/data"
	"github.com/go-rat/fiber-skeleton/internal/route"
	"github.com/go-rat/fiber-skeleton/internal/service"
)

import (
	_ "time/tzdata"
)

// Injectors from wire.go:

// initCli init command line.
func initCli() (*app.Cli, error) {
	koanf, err := bootstrap.NewConf()
	if err != nil {
		return nil, err
	}
	logger := bootstrap.NewLog(koanf)
	db, err := bootstrap.NewDB(koanf, logger)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(db)
	userService := service.NewUserService(userRepo)
	cli := route.NewCli(userService)
	command := bootstrap.NewCli(cli)
	appCli := app.NewCli(command)
	return appCli, nil
}
