name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: 'stable'
      - name: Set up environment
        run: |
          cp config/config.example.yml config/config.yml
      - name: Run tests
        run: go test -v -coverprofile="coverage.out" ./...
